apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: homework
data:
  webserver.conf: |
    server {
    listen       8000;
    location / {
        root   /homework;
        index  index.html;
    }
    }
